// Import the required functions from the Firebase SDK
// initializeApp → used to initialize Firebase
import { initializeApp } from "firebase/app";

// getAuth → used to enable Firebase Authentication
import { getAuth } from "firebase/auth";

// Firebase configuration object
// These values connect your app to your Firebase project
const firebaseConfig = {

  // API key is stored in .env file
  // In Vite, environment variables are accessed using import.meta.env
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY,

  // Auth domain for Firebase Authentication
  authDomain: "bitez-food-delivery.firebaseapp.com",

  // Unique project ID of your Firebase project
  projectId: "bitez-food-delivery",

  // Firebase Storage bucket
  storageBucket: "bitez-food-delivery.firebasestorage.app",

  // Sender ID for Firebase Cloud Messaging
  messagingSenderId: "437999508732",

  // Unique App ID generated by Firebase
  appId: "1:437999508732:web:77bf14ba4816c5e458cb79"
};

// Initialize Firebase app using the configuration
const app = initializeApp(firebaseConfig);

// Initialize Firebase Authentication using the app instance
// This allows login, signup, logout, etc.
const auth = getAuth(app);

// Export app and auth so they can be used in other files
// Example: login, signup, protected routes
export { app, auth };
